course-management/course/urls.py
from django.urls import include, path, re_path
from django.contrib import admin

from course.views import index, subject, course, enroll, time, news

handler404 = 'course.views.index.handler404'
handler500 = 'course.views.index.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', index.index, name='index'),
    re_path(r'^subject/', include([
        # If you want to add new urls for subjects, you have to add them
        # before the generic subject url (last entry).
        # Also add the string in question to the SUBJECT_DISALLOWED_NAMES in
        # 'forms.py'.
        re_path(r'^overview/$', subject.subject_overview, name='subject-overview'),
        re_path(r'^new/$', subject.create, name='create-subject'),
        re_path(r'^(?P<subjectname>[^/?]+)/', include([
            re_path(r'^$', subject.course_overview, name='subject'),
            re_path(r'^edit/$', subject.edit, name='edit-subject'),
            re_path(r'^delete/$', subject.delete, name='delete-subject'),
        ]))
    ])),


    re_path(r'^course/new/$', course.create, name='create-course'),

    re_path(r'^course/(?P<course_id>[0-9]+)/', include([
        re_path(r'^$', course.course, name='course'),
        re_path(r'^edit/$', course.edit_course, name='edit-course'),
        re_path(r'^delete/$', course.delete, name='delete-course'),
        re_path(r'^activate/$', course.toggle,
            {'active': True}, name='activate-course'),
        re_path(r'^deactivate/$', course.toggle,
            {'active': False}, name='deactivate-course'),
        re_path(r'^participants/$', course.participants_list,
            name='course-participants'),
        re_path(r'^notify/', include([
            re_path(r'^$', course.notify, name='notify-course'),
            re_path(r'^done/$', course.notify_done, name='notify-course-done'),
        ])),
        re_path(r'^contact/', include([
            re_path(r'^$', course.contact_teachers, name='contact-teachers'),
            re_path(r'^done/$', course.notify_done, name='contact-teachers-done'),
        ])),
        re_path(r'^register/', include([
            re_path(r'^$', enroll.add, name='register-course'),
            re_path(r'^remove/', include([
                re_path(r'^$', enroll.remove, name='unregister-course'),
                re_path(r'^(?P<student_id>[0-9]+)/$',
                    course.remove_student, name='unregister-course'),
            ])),
        ])),
        re_path(r'^schedule/', include([
            re_path(r'^edit/$', time.edit_slot, name='course-edit-slot'),
            re_path(r'^remove/(?P<slot_id>[0-9]+)/$',
                time.remove_slot, name='course-remove-slot'),
        ])),
        re_path(r'^teachers/', include([
            re_path(r'^add/$', course.add_teacher, name='add-teacher'),
            re_path(r'^remove/(?P<teacher_id>[0-9]+)/$',
                course.remove_teacher, name='remove-teacher'),
        ])),
        re_path(r'^attendee-list/$', course.attendee_list, name='attendee-list'),
    ])),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^accounts/', include('user.urls')),
    re_path(r'^news/create', news.create, name='create-news'),
    re_path(r'^news/(?P<news_id>[0-9]+)/', include([
        re_path(r'^edit/$', news.edit, name='edit-news'),
        re_path(r'^delete/$', news.delete, name='delete-news')
    ])),
    re_path(r'^privacy-policy/', index.privacy_policy, name='privacy-policy')
]

course-management/user/urls.py
from django.urls import include, re_path, path

from django.contrib.auth import views as auth_views
from django.contrib.auth import urls as auth_urls
from .views import user, register, verify, contact

urlpatterns = [
    re_path(r'^register/$', register.register, name='register'),
    re_path(r'^edit/$', user.modify, name='modify-user'),
    re_path(r'^privacy-policy/$', user.privacy_consent, name='privacy-policy-updated'),
    re_path(r'^delete/$', user.delete_account, name='delete-account'),
    re_path(r'^profile/$', user.profile, name='user-profile'),
    re_path(r'^profile/(?P<user_id>[0-9]+)/$', user.profile, name='user-profile'),
    re_path(r'^verify/(?P<type_>[\w\d_-]+)/$', verify.verify, name='verify'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(template_name='registration/logout.html')),
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='registration/login.html')),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='user/change_pass.html')),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='user/change_pass_success.html')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password-reset.html')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password-reset-done.html')),
    re_path(r'^contact/(?P<user_id>[0-9]+)/',
        contact.contact_form, name='contact-form'),
    re_path(r'^', include(auth_urls)),
]

course-management/course/models/course.py
from markdown import markdown
import logging

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import django.utils.timezone

from guardian.models import UserObjectPermission

from course.models import subject

from user.models import UserInformation, get_user_information

from util.html_clean import clean_for_description


ARCHIVE_STATUSES = (
    ('t', 'auto'),
    ('n', 'never'),
    ('a', 'archived'),
)

class Course(models.Model):
    teacher = models.ManyToManyField(UserInformation, related_name="teacher", blank=True)
    participants = models.ManyToManyField(UserInformation, blank=True, through='Participation')
    active = models.BooleanField(default=False)
    visible = models.BooleanField(default=False)
    subject = models.ForeignKey(subject.Subject, on_delete=models.CASCADE)
    max_participants = models.IntegerField()
    description = models.TextField(blank=True, default="")
    archiving = models.CharField(max_length=1, choices=ARCHIVE_STATUSES)
    start_time = models.DateField(default=django.utils.timezone.now)
    end_time = models.DateField(default=django.utils.timezone.now)

    class IsFull(Exception):
        pass

    class IsInactive(Exception):
        pass

    class IsInvisible(Exception):
        pass

    class IsNotEnrolled(Exception):
        pass

    class IsEnrolled(Exception):
        pass

    class IsArchived(Exception):
        pass


    def __str__(self):
        return self.subject.name

    def enroll(self, student):
        student = get_user_information(student)
        if self._is_participant(student):
            raise self.IsEnrolled
        elif not self.active:
            raise self.IsInactive
        elif self.is_archived():
            raise self.IsArchived
        else:
            if (self.participants.count()):
                ticket_number = Participation.objects.filter(course=self).reverse()[0].ticket_number + 1
            else:
                ticket_number = 1
            Participation.objects.create(participant=student, course=self, ticket_number=ticket_number)

    def unenroll(self, student):

        student = get_user_information(student)

        if self._is_participant(student):
            self.participants.remove(student)
        else:
            raise self.IsNotEnrolled
        # TODO: send notification to first in waiting list

    def _is_participant(self, student):
        student = get_user_information(student)
        return student in self.participants.all()

    def is_participant(self, student):
        return self._is_participant(get_user_information(student)) and not self.is_archived()

    @property
    def saturated(self):
        (curr, max) = self.saturation_level
        return curr >= max

    @property
    def joinable(self):
        """
        Returns whether this course can currently be joined.
        """
        return not self.saturated and self.is_active() and self.is_visible()

    @property
    def saturation_level(self):
        """
        Returns the ratio of currently enrolled participants to maximum allowed
        participants.
        """
        return self.participants.count(), self.max_participants

    @property
    def enrolled_students(self):
        return min(self.participants.count(), self.max_participants)

    @property
    def students_on_queue(self):
        return max(self.participants.count() - self.max_participants, 0)

    def get_description_as_html(self):
        return clean_for_description(markdown(self.description))

    def get_distinct_locations(self):
        return self.schedule.slots.values_list('location', flat=True).distinct()

    def get_locations(self):
        return self.schedule.slots.values_list('location', flat=True)

    def get_queue(self):
        return Participation.objects.filter(course=self)[self.max_participants:]

    def position_in_queue(self, student):
        queue = list(self.get_queue())
        if len(queue) == 0:
            return 0
        users = [p.participant for p in queue]
        user = get_user_information(student)
        if not user in users:
            return 0
        return users.index(user) + 1

    def as_context(self, student=None):
        participants_count, max_participants = self.saturation_level
        sub_name = self.subject.name
        context = {
            'title': sub_name,
            'course_id': self.id,
            'course': self,
            'backurl': reverse('subject', args=[sub_name]),
            'participants_count': participants_count,
            'max_participants': max_participants,
            'course_is_active': self.active,
            'course_is_visible': self.visible,
        }
        if student:
            student = get_user_information(student)
            context['position_in_queue'] = self.position_in_queue(student)
            context['is_subbed'] = student.course_set.filter(id=self.id).exists()

            if self.can_modify(student):
                context['can_modify'] = True
                context['is_teacher'] = self.is_teacher(student)
                context['students'] = self.participants.all()

        return context

    def can_be_archived(self):
        return self.archiving == 't'

    def is_archived(self):
        return self.archiving == 'a'

    def has_description(self):
        return self.description != ''

    def is_teacher(self, student):
        return self.teacher.filter(id=student.id).exists()

    def can_modify(self, student):
        """
        Formerly "is_teacher"; whether or not a user can change details of the course.
        """
        return student.user.has_perm('change_course', self) \
                and student.user.has_perm('delete_course', self)

    def is_active(self):
        return self.active and not self.is_archived()

    def is_visible(self):
        return self.visible and not self.is_archived()


class Notification(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ManyToManyField(UserInformation)

class Participation(models.Model):
    participant = models.ForeignKey(UserInformation, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    ticket_number = models.IntegerField()

    class Meta:
        ordering = ['ticket_number']

course-management/course/models/news.py
from django.db import models
from markdown import markdown
from util.html_clean import clean_for_description

class News(models.Model):
    headline = models.CharField(max_length=30)
    entry = models.TextField(blank=True, default="")
    author = models.CharField(max_length=301)
    modified = models.DateField(auto_now=True)

    def __str__(self):
        return self.headline

    def render_entry(self):
        return clean_for_description(markdown(self.entry))

    def render_date(self):
        return self.modified.strftime("%d.%m.%Y")

course-management/course/models/subject.py
from django.db import models
from markdown import markdown
from util.html_clean import clean_for_description

class Subject(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, default="")

    def __str__(self):
        return self.name

    def render_description(self):
        return clean_for_description(markdown(self.description))

    @classmethod
    def get_active(cls):
        """
        Return all subjects which have associated active courses.
        """
        # REVIEW
        # This does not work right now, I have no idea why
        # return cls.objects.annotate(
        #     course_count=models.Count(models.Q(course__active=True))
        # ).filter(course_count__gt=0)
        return filter(
            lambda subject: subject.is_active(),
            cls.objects.all()
        )

    @classmethod
    def get_visible(cls):
        """
        Return al subjects which have associated visible courses.
        """
        return filter(
            lambda subject:subject.is_visible(),
            cls.objects.all()
        )

    @classmethod
    def get_inactive(cls):
        """
        Return all subjects which do not have associated active courses.
        """
        return filter(
            lambda subject: not subject.is_active(),
            cls.objects.all()
        )

    @classmethod
    def get_invisible(cls):
        """
        Return all subjects which do not have associated visible courses.
        """
        return filter(
            lambda subject: not subject.is_visible(),
            cls.objects.all()
        )

    @property
    def active_courses(self):
        """
        Returns all associated courses which are active.
        """
        return self.course_set.filter(active=True, archiving='t')

    def visible_courses(self):
        """
        Returns all associated courses which are visible.
        """
        return self.course_set.filter(visible=True, archiving='t')

    def is_active(self):
        """
        Return true if this subject has any associated courses which are active.
        """
        return self.course_set.filter(active=True, archiving='t').exists()

    def is_visible(self):
        """
        Return true if this subject has any associated courses which are visible.
        """
        return self.course_set.filter(visible=True, archiving='t').exists()

course-management/course/views/enroll.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponseForbidden
from django.views.decorators.http import require_POST
from django.shortcuts import redirect, render
from django.utils.translation import gettext as _

from course.models.course import Course

from util.error.reporting import db_error
from util.routing import redirect_unless_target


@require_POST
@login_required()
def add(request, course_id):
    user = request.user
    stud = user.userinformation
    try:
        course = Course.objects.get(id=course_id)
    except Course.DoesNotExist:
        return db_error(request, _('Requested course does not exist.'))
    session = request.session

    if course.is_participant(stud):
        session['enroll-error'] = _('You are already enrolled in this course.')
    else:
        if 'enroll-error' in session:
            del session['enroll-error']
        try:
            course.enroll(stud)
        except Course.IsInactive:
            return HttpResponseForbidden()
        except Course.IsArchived:
            return HttpResponseForbidden()

    # redirect to course overview or specified target
    return redirect_unless_target(request, 'course', course_id)


@require_POST
@login_required()
def remove(request, course_id):
    stud = request.user.userinformation
    try:
        course = Course.objects.get(id=course_id)
    except Course.DoesNotExist:
        return db_error(request, _('Requested course does not exist.'))
    ps = course.participants

    if course.is_participant(stud):
        ps.remove(stud)
    else:
        request.session['enroll-error'] = _('You do not seem to be enrolled in this course.')
        return redirect('course', course_id)

    # redirect to course overview or specified target
    return redirect_unless_target(request, 'course', course_id)

course-management/course/views/index.py
from course.models import news
from django.shortcuts import render
from django.utils.translation import gettext as _


def index(request):
    return render(
        request,
        'index.html',
        {
            'title': _('Welcome'),
            'news': news.News.objects.order_by('-id')
        }
    )


def privacy_policy(request):
    return render(
        request,
        'privacy.html',
        {
            'title': _('Privacy Policy')
        }
    )


def handler404(request, exception, template_name="error/404.html"):
    response = render(request, template_name)
    response.status_code = 404
    return response


def handler500(request): #t, exception, template_name="error/500.html"):
    template_name = "error/500.html"
    response = render(request, template_name)
    response.status_code = 500
    return response

course-management/course/templates/base-shell.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
    <title>{% if title %}{{ title }} | {% endif %}{% trans "Course Manager" %}</title>
</head>
<body>
  {% block header %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">{% trans "Course Manager" %}</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        {% block header_nav %}
        {% endblock %}
      </div>
      {% endblock header %}
    </div>
  </nav>

  <div class="container-lg mt-md-4">
    <div class="row">
      <main class="col-md-9 mr-auto ml-auto mb-5">
        {% block content %}
        {% endblock content %}
      </main>
    </div>
  </div>
  <script type="text/javascript" src="{% static "js/jquery-3.4.1.slim.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

course-management/course/templates/base.html
{% extends 'base-shell.html' %}
{% load i18n %}

{% block header_nav %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'index' %}">{% trans 'News' %}</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'subject-overview' %}">{% trans 'Subjects' %}</a>
  </li>
  {% if perms.course_management.add_course or perms.course_management.add_subject or perms.news.add_news %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false" id="dropdownCreate">{% trans 'Create...' %}</a>
    <div class="dropdown-menu" aria-labelledby="dropdownCreate">
      {% if perms.course_management.add_subject %}
      <a class="dropdown-item" href="{% url 'create-subject' %}">{% trans 'New Subject' %}</a>
      {% endif %}
      {% if perms.course_management.add_course %}
      <a class="dropdown-item" href="{% url 'create-course' %}">{% trans 'New Course' %}</a>
      {% endif %}
      {% if perms.news.add_news %}
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'create-news' %}">{% trans 'News Item' %}</a>
      {% endif %}
    </div>
  </li>
  {% endif %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false" id="dropdownAbout">{% trans 'About' %}</a>
    <div class="dropdown-menu" aria-labelledby="dropdownAbout">
      <a class="dropdown-item" href="https://www.ifsr.de/impressum">{% trans 'Imprint' %}</a>
      <a class="dropdown-item" href="{% url 'privacy-policy' %}">{% trans 'Privacy Policy' %}</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="https://github.com/fsr/course-management/issues/new">{% trans 'Report an Issue' %}</a>
    </div>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'user-profile' %}">{% trans 'Your Courses' %}</a>
  </li>
  <li class="nav-item dropdown">
    <!-- <a class="nav-link" href="{% url 'modify-user' %}">{% trans 'Settings' %}</a> -->
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false" id="dropdownSettings">{% trans 'Settings' %}</a>
    <div class="dropdown-menu" aria-labelledby="dropdownSettings">
      <a class="dropdown-item" href="{% url 'modify-user' %}">{% trans 'Your Profile' %}</a>
      <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Change Password' %}</a>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'register' %}">{% trans "Sign up" %}</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'login' %}{% if not no_login_redirect and not request.path == logout_url %}?next={{ request.path }}{% endif %}">{% trans 'Login' %}</a>
  </li>
  {% endif %}
</ul>
{% endblock %}

course-management/course/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1 class="mb-3">{% trans "Current News" %}</h1>

{% for entry in news %}
<div class="shadow p-3 mb-5 bg-light rounded">
  <h3>{{ entry.headline }}</h3>
  <small><i>{{ entry.author }}</i> - {{ entry.render_date }}</small>
  <hr>
  <p>{{ entry.render_entry|safe }}</p>
  {% if perms.news.change_news or perms.news.delete_news %}
  <div class="row m-3">
    <div class="ml-auto">
      {% if perms.news.change_news %}
      <a href="{% url 'edit-news' entry.id %}" type="button" class="btn btn-outline-success">{% trans 'Edit' %}</a>
      {% endif %}
      {% if perms.news.delete_news %}
      <a href="{% url 'delete-news' entry.id %}" type="button" class="btn btn-outline-warning">{% trans 'Delete' %}</a>
      {% endif %}
    </div>
  </div>
  {% endif %}
</div>
{% empty %}
<div class="p-4">
  <i>{% trans 'There are currently no news.' %}</i>
</div>
{% endfor %}

<div class="p-3 mb-5">
  <h2>{% trans 'Welcome to the Course Management System!' %}</h2>
  {% blocktrans %}
    <p>Welcome! It's nice to see you here. This is the course management system operated by the student representatives of the Computer Science faculty at TU Dresden. Here, you can enroll for various programming courses that are offered in the current semester.</p>
    <p>Usually, all courses we offer are held by fellow students who have taken a particular interest in sharing their knowledge about programming languages and techniques with others. While these courses are therefore not acknowledged by the examination office, you can use them to learn new skills or programming languages.</p>
  {% endblocktrans %}
</div>
{% endblock %}

course-management/course/templates/privacy.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Privacy Policy" %}</h1>

  {% include "privacy-policy.html" %}
{% endblock %}